---
  name: Deploy component
  
  triggers:
    - type: webhook
  
  vars:
    path: "CHANGEME(Such as /opt/hilton/hilton-devops)"
    slack_webhook: "CHANGEME"
  
  prompt:
    environment:
      type: select
      options:
        - dev
        - staging
        - prod
    component:
      type: select
      options:
        - CHANGEME
    version: master
  
  actions:
    - name: Notify in Slack
      type: slack
      message: |
        {% if webhook_content is defined and webhook_content.environment and webhook_content.version and webhook_content.component %}
          {% set environment = webhook_content.environment %}
          {% set version = webhook_content.version %}
          {% set component = webhook_content.component %}
        {% endif %}
  
        '[CHANGEME | {{ environment }}] Starting Deploy process for component: {{ component }}:{{ version }}'
  
    - name: Trigger deploy
      type: bash
      cmd: |
        {% if webhook_content is defined and webhook_content.environment and webhook_content.version and webhook_content.component %}
          {% set environment = webhook_content.environment %}
          {% set version = webhook_content.version %}
          {% set component = webhook_content.component %}
        {% endif %}
  
        cd {{ path }}/devops/ansible &&
        ansible-playbook -i inventory.{{ environment }} deploy.yml \
          --vault-password-file /var/lib/pipelines/secure/CHANGEME.key \
          -u wcladmin -b \
          -e "walmart_component_version={{ version }}" \
          -e component={{ component }}
  
    - name: Notify in Slack
      type: slack
      always_run: true
      message: |
        {% if webhook_content is defined and webhook_content.environment and webhook_content.version and webhook_content.component %}
          {% set environment = webhook_content.environment %}
          {% set version = webhook_content.version %}
          {% set component = webhook_content.component %}
        {% endif %}
  
        '[CHANGEME | {{ environment }}] *{{ status }}* Deploy process for component: {{ component }}:{{ version }}'
  